module:
  allowed_formats: 0
  base_module: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_plugins: 0
  client_ip: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  config_filter: 0
  config_split: 0
  config_translation: 0
  contact: 0
  contact_form: 0
  cookies: 0
  ctools: 0
  datetime: 0
  dblog: 0
  drush_language: 0
  dynamic_page_cache: 0
  editor: 0
  editor_advanced_link: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  gin_toolbar: 0
  hreflang: 0
  image: 0
  imageapi_optimize: 0
  language: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_breadcrumb: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  redirect: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  vbo_export: 0
  views_bulk_operations: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  xmlsitemap: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  stable: 0
  classy: 0
  runroom: 0
  claro: 0
  gin: 0
profile: minimal
langcode: es
