module:
  block: 0
  breakpoint: 0
  ckeditor: 0
  config_translation: 0
  contact: 0
  ctools: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  kint: 0
  language: 0
  link: 0
  locale: 0
  menu_ui: 0
  metatag: 0
  metatag_views: 0
  node: 0
  page_cache: 0
  path: 0
  redirect: 0
  runroom: 0
  shortcut: 0
  system: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  runroom: 0
profile: minimal
