definitions:
  contact__site_page:
    enabled: false
    menu_name: footer
    parent: ''
    expanded: false
    weight: 0
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
langcode: es
