module:
  block: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  ckeditor: 0
  clientside_validation: 0
  clientside_validation_jquery: 0
  config_translation: 0
  contact: 0
  contact_storage: 0
  content_translation: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  eu_cookie_compliance: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  hipartners_general: 0
  image: 0
  kint: 0
  language: 0
  link: 0
  locale: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  minifyjs: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  path: 0
  path_redirect_import: 0
  redirect: 0
  redirect_404: 0
  redirect_by_ip: 0
  responsive_image: 0
  responsive_tables_filter: 0
  search: 0
  shortcut: 0
  sitemap: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  tmgmt: 0
  tmgmt_config: 0
  tmgmt_content: 0
  tmgmt_file: 0
  tmgmt_language_combination: 0
  tmgmt_local: 0
  tmgmt_locale: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  update: 0
  user: 0
  views: 0
  views_ui: 0
  viewsreference: 0
  xmlsitemap: 0
  xmlsitemap_custom: 0
  xmlsitemap_engines: 0
  youtube: 0
  pathauto: 1
  better_formats: 100
  minimal: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  hipartners: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
