_core:
  default_config_hash: IhwTepsVwtbtbcT5GzQKhCXDCRvbk3MNkWqPiuiZ10s
langcode: es
theme: runroom
defaults:
  sender: swiftmailer
  formatter: swiftmailer
modules:
  swiftmailer:
    none:
      sender: swiftmailer
      formatter: swiftmailer
