determine_menu: true
disable_admin_page: true
append_current_page: true
current_page_as_link: false
stop_on_first_match: false
append_member_page: false
member_page_as_link: false
remove_home: false
add_home: false
home_as_site_name: false
exclude_empty_url: false
derived_active_trail: false
menu_breadcrumb_menus:
  main:
    enabled: 1
    weight: -10
_core:
  default_config_hash: xZ4J91eWz9ofH6dVhYAwxZiL-15jnspJBOmGtRDtFSM
langcode: es
