page_title: Sitemap
message:
  value: ''
  format: complete
show_front: false
show_titles: false
show_books: {  }
books_expanded: true
show_menus:
  sitemap-menu: sitemap-menu
  accionistas: '0'
  account: '0'
  admin: '0'
  company: '0'
  devel: '0'
  footer: '0'
  main: '0'
  tools: '0'
show_menus_hidden: false
show_vocabularies:
  hotel_brand: '0'
  hotel_category: '0'
  hotel_contract: '0'
  hotel_operator: '0'
  hotel_segment: '0'
  news_type: '0'
  subject_contact_form: '0'
show_description: true
show_count: true
vocabulary_depth: -1
term_threshold: 0
forum_threshold: -1
rss_front: rss.xml
show_rss_links: 1
rss_taxonomy: -1
css: true
order:
  front: -50
  menus_tools: -50
  vocabularies_news_type: -50
  vocabularies_hotel_segment: -50
  vocabularies_hotel_operator: -50
  vocabularies_hotel_contract: -50
  vocabularies_hotel_category: -50
  vocabularies_hotel_brand: -50
  menus_sitemap-menu: -50
  menus_accionistas: -50
  menus_main: -50
  menus_footer: -50
  menus_devel: -50
  menus_company: -50
  menus_admin: -50
  menus_account: -50
  vocabularies_subject_contact_form: -50
_core:
  default_config_hash: yUNkiSB-fp4pyUb6B2L9HiiCdISBDvK7r1v9_XkGUaQ
langcode: es
