name: 'Runroom Archetype'
mail: software@runroom.com
slogan: ''
page:
  403: ''
  404: ''
  front: /home
admin_compact_mode: false
weight_select_max: 100
langcode: es
default_langcode: es
mail_notification: ''
