---
- name: Create directories
  file:
    path: '{{ ansible_env.HOME }}/{{ item.folder }}'
    state: directory
  with_items: '{{ server.links }}'
  when: server.links is defined

- name: Remove symbolic links
  file:
    path: '{{ item.dest }}/{{ item.folder }}'
    state: absent
  with_items: '{{ server.links }}'
  when: server.links is defined

- name: Create symbolic links
  file:
    src: '{{ ansible_env.HOME }}/{{ item.folder }}'
    path: '{{ item.dest }}/{{ item.folder }}'
    state: link
  with_items: '{{ server.links }}'
  when: server.links is defined
