version: "3.8"

# Prod
# volumes:
#     data-volume:

services:
    app:
        build:
            context: .
            target: fpm-dev
        volumes:
            - .:/usr/app/:cached
            - .docker/app-dev/extra.ini:/usr/local/etc/php/conf.d/extra.ini
            - .docker/app-dev/www.conf:/usr/local/etc/php-fpm.d/www.conf
            - /usr/app/node_modules/
            - /usr/app/web/sites/default/tmp/
            - /usr/app/web/sites/default/files/php/
            - /usr/app/web/sites/default/files/languages/
            - /usr/app/web/sites/default/files/translations/
        environment:
            - XDEBUG_CONFIG
        # Prod
        # depends_on:
        #     - database
        # build:
        #     context: .
        #     target: fpm-prod
        # volumes:
        #     - data-volume:/usr/app/web
    nginx:
        image: nginx:1.21
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - .docker/nginx-dev/nginx.conf:/etc/nginx/nginx.conf
            - .certs:/usr/app/.certs:ro,cached
            - ./web:/usr/app/web:ro,cached
        # Prod
        # depends_on:
        #     - app
        # volumes:
        #     - .docker/nginx-prod/nginx.conf:/etc/nginx/nginx.conf
        #     - data-volume:/usr/app/web
    database:
        image: postgres:14.1
        environment:
            POSTGRES_DB: drupal
            POSTGRES_USER: drupal
            POSTGRES_PASSWORD: drupal
        ports:
            - 8432:5432
    mailhog:
        image: mailhog/mailhog
        ports:
            - 8025:8025
