galaxy_info:
  author: Jeff Geerling
  description: A role to configure various odds and ends in Drupal VM prior to installing Drupal.
  company: Midwestern Mac, LLC
  issue_tracker_url: https://github.com/geerlingguy/drupal-vm/issues
  license: MIT
  min_ansible_version: 2.2

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - precise
        - raring
        - saucy
        - trusty
        - xenial

  galaxy_tags:
    - nginx
    - drupal
    - vm
    - vagrant

dependencies:
  - { role: geerlingguy.nginx, when: drupalvm_webserver == 'nginx' }
