label: 'Página principal'
description: 'Todo el contenido promovido a la página principal.'
display:
  default:
    display_options:
      empty:
        area_text_custom:
          content: 'Todavía no se ha creado contenido para la portada.'
        title:
          title: 'Bienvenido a [site:name]'
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
      pager:
        options:
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
          tags:
            previous: '‹ Anterior'
            next: 'Siguiente >'
            first: '« Primero'
            last: 'Último »'
    display_title: Máster
  feed_1:
    display_title: Agregador
  page_1:
    display_title: Página
