---
- name: Add ppa repository
  become: true
  apt_repository:
    repo: ppa:ondrej/apache2

- name: Install apache
  become: true
  apt:
    name: apache2
    state: latest

- name: Enable apache modules
  become: true
  apache2_module:
    name: '{{ item }}'
  with_items: '{{ apache.modules }}'
  notify: Restart apache

- name: Copy apache config
  become: true
  template:
    src: '{{ item }}'
    dest: '/etc/apache2/{{ item }}'
  with_items:
    - common.conf
    - htaccess.conf
  notify: Restart apache

- name: Change default apache site
  become: true
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify: Restart apache
