vagrant_hostname: drupal.local
vagrant_machine_name: drupal
vagrant_ip: 192.168.88.66
vagrant_synced_folders:
  - local_path: .
    destination: /vagrant
    type: ''
    create: true

# Composer project settings.
drupal_build_makefile: false
drupal_build_composer_project: false
drupal_build_composer: false
drupal_composer_install_dir: /vagrant
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_composer_dependencies: []

# Drupal install settings.
drupal_site_name: Archetype Drupal
drupal_install_site: true
drupal_install_profile: minimal
drupal_site_install_extra_args:
  - --config-dir=/vagrant/config/base

# Other overrides.
php_version: "7.1"

installed_extras:
  - adminer
  - drupalconsole
  - drush
  - drupal
  - mailhog
  - nodejs
  - pimpmylog
  - xdebug

php_memory_limit: 512M
