vagrant_hostname: drupal.local
vagrant_ip: 192.168.88.66
vagrant_synced_folders:
  - local_path: .
    destination: /vagrant
    type: ''
    create: true

# SSH settings.
ssh_home: "{{ drupal_composer_install_dir }}"

# Composer project settings.
drupal_composer_install_dir: /vagrant

# Other overrides.
php_version: "7.1"

# Database
drupal_db_file: drupal-vm/provisioning/files/dump.sql

# Drush
configure_drush_aliases: false

installed_extras:
  - adminer
  # - drupalconsole
  - drush
  - mailhog
  - nodejs
  - pimpmylog
  - xdebug

php_memory_limit: 512M

extra_packages:
  - sqlite
  - libpng16-16
