---

- name: Configuring module
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: "{{ newrelic_user }}"
    group: "{{ newrelic_group }}"
    mode: "0640"
  notify: restart newrelic
  with_items:
    - "etc/newrelic/nrsysmond.cfg"

- name: Configuring user groups
  user:
    name: "{{ newrelic_user }}"
    groups: "{{ newrelic_groups|join(',') }}"
    append: yes
  when: not newrelic_disable_docker
