---
- name: clear opcache
  command: >
    {{ drush_path }} eval
      "if (function_exists('apc_clear_cache')) {
        apc_clear_cache();
      }
      if (function_exists('opcache_reset')) {
        opcache_reset();
      }"
  args:
    chdir: "{{ drupal_core_path }}"
