---
- name: Add mysql apt signing key.
  become: true
  apt_key:
    url: https://repo.mysql.com/RPM-GPG-KEY-mysql

- name: Install the official mysql repo
  become: true
  apt:
    deb: https://dev.mysql.com/get/mysql-apt-config_0.8.11-1_all.deb
    state: present

- name: Install mysql packages
  become: true
  apt:
    name:
      - mysql-server
      - mysql-client
      - python-mysqldb
    update_cache: yes
    state: latest

- name: Modify settings on mysqld.cnf
  become: true
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '#?{{ item.setting }} ?=.*'
    line: '{{ item.setting }} = {{ item.value }}'
  with_items:
    - { setting: default-authentication-plugin, value: mysql_native_password }
  notify: Restart mysql

- meta: flush_handlers

- name: Drop database
  become: true
  mysql_db:
    name: '{{ mysql.database }}'
    state: absent
  tags:
    - database

- name: Create database
  become: true
  mysql_db:
    name: '{{ mysql.database }}'
    encoding: utf8mb4
  tags:
    - database

- name: Import database
  become: true
  mysql_db:
    name: '{{ mysql.database }}'
    state: import
    target: /vagrant/{{ mysql.dump }}
  when: mysql.dump
  tags:
    - database

- name: Create user
  become: true
  mysql_user:
    name: '{{ mysql.user }}'
    password: '{{ mysql.password }}'
    host: '%'
    priv: '{{ mysql.database }}.*:ALL'
