---
- name: Install mysql packages
  become: true
  apt:
    name:
      - mysql-server
      - mysql-client
      - python-mysqldb
    state: latest

- name: Allow external connections
  become: true
  lineinfile:
    path: '/etc/mysql/mysql.conf.d/mysqld.cnf'
    regexp: '^{{ item }}(.*)$'
    line: '#{{ item }}\1'
    backrefs: yes
  with_items:
    - skip-external-locking
    - bind-address
  notify: Restart mysql

- name: Drop database
  become: true
  mysql_db:
    name: '{{ mysql.database }}'
    state: absent
  tags:
    - database

- name: Create database
  become: true
  mysql_db:
    name: '{{ mysql.database }}'
    encoding: utf8mb4
  tags:
    - database

- name: Import database
  become: true
  mysql_db:
    name: '{{ mysql.database }}'
    state: import
    target: /vagrant/{{ mysql.dump }}
  when: mysql.dump
  tags:
    - database

- name: Create user
  become: true
  mysql_user:
    name: '{{ mysql.user }}'
    password: '{{ mysql.password }}'
    host: '%'
    priv: '{{ mysql.database }}.*:ALL'
