---
- name: Add ppa repository
  become: true
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php fpm
  become: true
  apt:
    name: 'php{{ php.version }}-fpm'
    state: latest

- name: Ensure main php is installed
  become: true
  apt:
    name: 'php{{ php.version }}'
    state: latest

- name: Install php extensions
  become: true
  apt:
    name: "{{ php.extensions|map('regex_replace', '(.*)', 'php' ~  php.version ~ '-\\1')|list }}"
    state: latest
  when: php.extensions is defined
  notify: Restart fpm

- name: Create symbolic link
  become: true
  file:
    src: '/usr/bin/{{ item }}{{ php.version }}'
    path: '/etc/alternatives/{{ item }}'
    state: link
    force: true
  with_items:
    - php
    - phar
    - phar.phar
    - phpdbg

- name: Modify settings on php.ini
  become: true
  lineinfile:
    path: '/etc/php/{{ php.version }}/{{ item[0] }}/php.ini'
    regexp: ';?{{ item[1].setting }} ?=.*'
    line: '{{ item[1].setting }} = {{ item[1].value }}'
  with_nested:
    - [cli, fpm, phpdbg]
    - '{{ php.settings }}'
  notify: Restart fpm

- name: Modify settings on fpm www.conf
  become: true
  lineinfile:
    path: '/etc/php/{{ php.version }}/fpm/pool.d/www.conf'
    regexp: ';?{{ item.setting }} ?=.*'
    line: '{{ item.setting }} = {{ item.value }}'
  with_items: '{{ php.fpm }}'
  notify: Restart fpm
