---
- name: Set the PHP webserver daemon correctly when nginx is in use.
  set_fact:
    php_webserver_daemon: nginx
  when: drupalvm_webserver == 'nginx'
  tags: ['webserver', 'database', 'php']

- name: Ensure PHP version -specific workspace directory exists.
  file:
    path: "/root/php{{ php_version }}"
    state: directory
    mode: 0775
  tags: ['php', 'xdebug']
