---
- name: Import the nodesource gpg key into apt
  become: true
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: '68576280'

- name: Add nodesource deb repository
  become: true
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ node.source }} {{ ansible_distribution_release }} main'

- name: Add nodesource deb-src repository
  become: true
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_{{ node.source }} {{ ansible_distribution_release }} main'

- name: Add nodesource repository preferences
  become: true
  template:
    src: deb_nodesource_com_node.pref
    dest: /etc/apt/preferences.d/deb_nodesource_com_node.pref

- name: Install node
  become: true
  apt:
    name: nodejs
    state: latest

- import_tasks: yarn.yaml
