---
- src: arknoll.selenium
  version: 2.2.1
- src: thom8.php-upload-progress
  version: 1.0.1
- src: franklinkim.newrelic
  version: 1.6.0
- src: geerlingguy.adminer
  version: 1.1.1
- src: geerlingguy.apache
  version: 2.1.1
- src: geerlingguy.apache-php-fpm
  version: 1.0.2
- src: geerlingguy.blackfire
  version: 1.0.0
- src: geerlingguy.composer
  version: 1.6.1
- src: geerlingguy.daemonize
  version: 1.1.1
- src: geerlingguy.drupal
  version: 2.2.2
- src: geerlingguy.drupal-console
  version: 1.1.0
- src: geerlingguy.drush
  version: 2.0.1
- src: geerlingguy.elasticsearch
  version: 2.1.3
- src: geerlingguy.firewall
  version: 2.2.1
- src: geerlingguy.git
  version: 1.3.0
- src: geerlingguy.java
  version: 1.7.4
- src: geerlingguy.mailhog
  version: 2.1.3
- src: geerlingguy.memcached
  version: 1.0.7
- src: geerlingguy.mysql
  version: 2.7.2
- src: geerlingguy.nginx
  version: 2.3.2
- src: geerlingguy.nodejs
  version: 4.1.1
- src: geerlingguy.php
  version: 3.4.5
- src: geerlingguy.php-memcached
  version: 2.0.0
- src: geerlingguy.php-mysql
  version: 2.0.1
- src: geerlingguy.php-pecl
  version: 1.3.0
- src: geerlingguy.php-pgsql
  version: 1.0.0
- src: geerlingguy.php-redis
  version: 3.1.0
- src: geerlingguy.php-tideways
  version: 1.1.0
- src: geerlingguy.php-versions
  version: 1.1.0
- src: geerlingguy.php-xdebug
  version: 2.3.1
- src: geerlingguy.php-xhprof
  version: 2.2.2
- src: geerlingguy.pimpmylog
  version: 1.0.2
- src: geerlingguy.postfix
  version: 1.1.0
- src: geerlingguy.postgresql
  version: 1.3.0
- src: geerlingguy.redis
  version: 1.5.1
- src: geerlingguy.repo-remi
  version: 1.2.0
- src: geerlingguy.ruby
  version: 2.4.2
- src: geerlingguy.security
  version: 1.5.0
- src: geerlingguy.solr
  version: 3.5.5
- src: geerlingguy.varnish
  version: 2.0.0
