---
# Defaults set by `ansible-role-php` with the addition of `php-pecl-yaml` and `php-mcrypt`.
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-gd
  - php-imap
  - php-ldap
  - php-mbstring
  - php-mcrypt
  - php-opcache
  - php-pdo
  - php-pear
  - php-pecl-apcu
  - php-xml
  - php-xmlrpc
  - php-pecl-yaml
