<?php

declare(strict_types=1);

function base_module_theme(): array
{
    return [
        'styleguide' => [
            'variables' => [
                'title' => null,
            ],
        ],
    ];
}

function base_module_language_switch_links_alter(array &$links): void
{
    $node = \Drupal::routeMatch()->getParameter('node');

    if (null !== $node) {
        foreach ($links as $langCode => $link) {
            if (null === $node->getTranslationStatus($langCode)
                || !$node->getTranslation($langCode)->isPublished()) {
                unset($links[$langCode]);
            }
        }
    }
}
