<?php

function base_module_theme($existing, $type, $theme, $path)
{
    return [
        'styleguide' => [
            'variables' => [
                'title' => null,
            ],
        ],
    ];
}

function base_module_language_switch_links_alter(array &$links, $type, $path)
{
    $node = \Drupal::routeMatch()->getParameter('node');

    if (!\is_null($node)) {
        foreach ($links as $langCode => $link) {
            if (\is_null($node->getTranslationStatus($langCode))
                || !$node->getTranslation($langCode)->isPublished()) {
                unset($links[$langCode]);
            }
        }
    }
}
