services:
    app:
        build:
            target: app-prod
        depends_on:
            database:
                condition: service_healthy
        environment:
            APP_ENV: "${APP_ENV:-prod}"
            RESET_DATABASE: "${RESET_DATABASE:-false}"
            MIGRATE_DATABASE: "${MIGRATE_DATABASE:-false}"
        volumes:
            - ../web/sites/default/files:/usr/app/web/sites/default/files
        healthcheck:
            test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
            start_period: 2m
            interval: 10s
    database:
        healthcheck:
            test: pg_isready --username $${POSTGRES_USER}
            interval: 5s
