services:
    app:
        build:
            target: fpm-prod
        depends_on:
            database:
                condition: service_healthy
        environment:
            APP_ENV: "${APP_ENV:-prod}"
            RESET_DATABASE: "${RESET_DATABASE:-false}"
            MIGRATE_DATABASE: "${MIGRATE_DATABASE:-false}"
        volumes:
            - ../web/sites/default/files:/usr/app/web/sites/default/files
        healthcheck:
            test: ["CMD", "healthcheck"]
            start_period: 2m
            interval: 10s
    nginx:
        build:
            target: nginx-prod
        depends_on:
            app:
                condition: service_started
        volumes:
            - ../web/sites/default/files:/usr/app/web/sites/default/files
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost"]
            start_period: 2m
            interval: 10s
    database:
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
