---
- name: Import the yarn gpg key into apt
  become: true
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg

- name: Add yarn deb repository
  become: true
  apt_repository:
    repo: 'deb http://dl.yarnpkg.com/debian/ stable main'

- name: Install yarn
  become: true
  apt:
    name: yarn
    state: latest
