---
- hosts: all
  vars_files:
    - vars.yaml
  roles:
    - server
    - mysql
    - php
    - { role: apache, when: webserver.type == 'apache' }
    - { role: nginx, when: webserver.type == 'nginx' }
    - drupal
    - composer
    - app
