---
- name: Enable forward agent
  lineinfile:
    dest: '/etc/ssh/ssh_config'
    regexp: '#(\s*)ForwardAgent.*'
    line: ' \1ForwardAgent yes'
    backrefs: yes

- name: Install composer vendors
  become: false
  composer:
    no_dev: no
    working_dir: /vagrant

- name: Install drupal
  become: false
  command: drupal initialize
  args:
    chdir: /vagrant
