---
services: docker

env:
  - distro: centos7
  - distro: centos6
  - distro: ubuntu1604
  - distro: ubuntu1404

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Send an email via mhsendmail.
  - 'docker exec --tty ${container_id} env TERM=xterm sh -c "cat /etc/ansible/roles/role_under_test/tests/message | /opt/mailhog/mhsendmail johndoe@example.com"'

  # Test retrieving messages via MailHog API.
  - 'docker exec --tty ${container_id} env TERM=xterm sh -c "curl http://localhost:8025/api/v2/messages | grep id"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
