<?php

/**
 * @file
 * Contains hipartners_general.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\user\PrivateTempStoreFactory;

/**
 * Implements hook_help().
 */
function hipartners_general_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the hipartners_general module.
    case 'help.page.hipartners_general':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Hi partners custom functionalities') . '</p>';
      return $output;

    default:
  }
}

function hipartners_general_theme($existing, $type, $theme, $path) {
  return array(
    'relatedHotelsBlock' => array(
      'variables' => array(
        'title' => NULL,
        'previous' => NULL,
        'next' => NULL,
      ),
    ),
    'generalMeetingsBlock' => array(
      'variables' => array(
        'list' => NULL,
        'node' => NULL,
      ),
    ),
    'styleguide' => array(
      'variables' => array(),
    ),
    'contact_us_mail' => array(
      'variables' => array(
        'name' => NULL,
        'phone' => NULL,
        'email' => NULL,
        'text' => NULL,
        'reason' => NULL,
      ),
    ),
    'apply_job_mail' => array(
      'variables' => array(
        'name' => NULL,
        'phone' => NULL,
        'email' => NULL,
        'linkedin' => NULL,
        'fieldUri' => NULL,
        'baseUrl' => NULL,
      ),
    ),
    'emissionBrochuresBlock' => array(
      'variables' => array(
        'residence' => NULL,
        'physically' => NULL,
        'form' => NULL,
        'content' => NULL,
      ),
    ),
  );
}

function hipartners_general_mail_alter(&$message) {
  global $base_url;

  if (!empty($message['id']) && $message['id'] === 'contact_page_mail') {
    $contact_message = $message['params']['contact_message'];
    $contact_form_id = $message['params']['contact_form']->id();

    if ($contact_form_id === 'contacto') {
      $name = $contact_message->get('field_name')->getString();
      $phone = $contact_message->get('field_phone')->getString();
      $email = $contact_message->get('field_email')->getString();

      $text = '';
      if (!empty($contact_message->get('field_message')->getValue())) {
        $text = $contact_message->get('field_message')->getValue()[0]['value'];
      }

      $reason = '';
      if (!empty($contact_message->get('field_reason')->getValue())) {
        $reason = $contact_message->get('field_reason')->getValue()[0]['value'];
      }

      $subject = '';
      if (!empty($contact_message->get('field_custom_subject')->getValue())) {
        $subject = $contact_message->get('field_custom_subject')->getValue()[0]['target_id'];
      }


      $message['body'] = [];
      $body_data = [
        '#theme' => 'contact_us_mail',
        '#name' => $name,
        '#phone' => $phone,
        '#email' => $email,
        '#text' => $text,
        '#reason' => $reason,
      ];
      $body_content = \Drupal::service('renderer')->renderPlain($body_data);
      $message['body'][] = $body_content;
    }

  if ($contact_form_id === 'form_apply_job') {
    $name = $contact_message->get('field_name')->getString();
    $phone = $contact_message->get('field_phone')->getString();
    $email = $contact_message->get('field_email')->getString();

    $linkedin = '';
    if (!empty($contact_message->get('field_linkedin')->getString())) {
      $linkedin = $contact_message->get('field_linkedin')->getString();
    }

    $fileUri = '';
    if (!empty($contact_message->get('field_attach_file')->getValue()[0]['target_id'])) {
      $target_id = $contact_message->get('field_attach_file')->getValue()[0]['target_id'];
      $file = \Drupal::service('entity_type.manager')->getStorage("file")->load($target_id);
      if($file) {
        $fileUri = $file->get('uri')->getValue()[0]['value'];
      }
    }

    $message['body'] = [];
    $body_data = [
      '#theme' => 'apply_job_mail',
      '#name' => $name,
      '#phone' => $phone,
      '#email' => $email,
      '#linkedin' => $linkedin,
      '#fieldUri' => $fileUri,
      '#baseUrl' => $base_url,
    ];
    $body_content = \Drupal::service('renderer')->renderPlain($body_data);
    $message['body'][] = $body_content;
  }
	}
}

/**
 * Implements hook_form_alter().
 */
function hipartners_general_form_alter(&$form, $form_state, $form_id) {

  if (strpos($form_id, 'contact_message_contacto_form') !== FALSE ||
      strpos($form_id, 'contact_message_form_apply_job_form') !== FALSE ||
    strpos($form_id, 'contact_message_qib_form_form') !== FALSE) {
    $form['actions']['preview']['#access'] = FALSE;
  }

  if ($form_id == 'contact_message_contacto_form') {
    $form['actions']['submit']['#submit'][] = 'contact_form_submit';
  }

  if ($form_id == 'contact_message_form_apply_job_form') {
    $form['actions']['submit']['#submit'][] = 'apply_job_form_submit';
  }

  if ($form_id == 'contact_message_qib_form_form') {
    $form['actions']['submit']['#submit'][] = 'qib_form_submit';
  }

}

function contact_form_submit(&$form, FormStateInterface $form_state) {
	drupal_set_message(t('your message has been sent successfully'));
	$node = \Drupal::routeMatch()->getParameter('node');
	$id = $node->id();
	$form_state->setRedirect('entity.node.canonical', ['node' => $id]);
}

function apply_job_form_submit(&$form, FormStateInterface $form_state) {
	drupal_set_message(t('your request has been sent successfully'));
	$node = \Drupal::routeMatch()->getParameter('node');
	$id = $node->id();
	$form_state->setRedirect('entity.node.canonical', ['node' => $id]);
}

function qib_form_submit(&$form, FormStateInterface $form_state) {
  drupal_set_message(t('your confirmation has been sent successfully'));
  $node = \Drupal::routeMatch()->getParameter('node');
  $id = $node->id();
  $form_state->setRedirect('entity.node.canonical', ['node' => $id]);
}