<?php
/**
 * @file
 * Drush aliases for the Platform.sh project "HI Partners".
 *
 * This file is auto-generated by the Platform.sh CLI.
 *
 * WARNING
 * This file may be regenerated at any time.
 * - User-defined aliases will be preserved.
 * - Aliases for active environments (including any custom additions) will be preserved.
 * - Aliases for deleted or inactive environments will be deleted.
 * - All other information will be deleted.
 */


// Automatically generated alias for the local environment, application "php"
$aliases['_local'] = array (
  'root' => '/vagrant/web',
  'platformsh-cli-auto-remove' => true,
);

// // Automatically generated alias for the environment "development", application "php".
// $aliases['development'] = array (
//   'uri' => 'http://development-q5nzhaa-fa7puzdbyyltu.eu.platform.sh/',
//   'remote-host' => 'ssh.eu.platform.sh',
//   'remote-user' => 'fa7puzdbyyltu-development-q5nzhaa',
//   'root' => '/app/web',
//   'platformsh-cli-auto-remove' => true,
//   'command-specific' =>
//   array (
//     'site-install' =>
//     array (
//       'sites-subdir' => 'default',
//     ),
//   ),
// );

// // Automatically generated alias for the environment "Master", application "php".
// $aliases['master'] = array (
//   'uri' => 'http://master-7rqtwti-fa7puzdbyyltu.eu.platform.sh/',
//   'remote-host' => 'ssh.eu.platform.sh',
//   'remote-user' => 'fa7puzdbyyltu-master-7rqtwti',
//   'root' => '/app/web',
//   'platformsh-cli-auto-remove' => true,
//   'command-specific' =>
//   array (
//     'site-install' =>
//     array (
//       'sites-subdir' => 'default',
//     ),
//   ),
// );
