name: QA

on:
    push:
        branches: [main]
    pull_request:

jobs:
    php:
        name: PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ["8.1"]
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  tools: cs2pr
            - uses: ramsey/composer-install@v2
            - run: composer php-cs-fixer -- --dry-run --format=checkstyle | cs2pr
            - run: composer phpstan -- --error-format=checkstyle | cs2pr
            - run: composer rector -- --dry-run
            - run: composer normalize --dry-run
    node:
        name: Node ${{ matrix.node }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["18.x"]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - uses: bahmutov/npm-install@v1
            - run: npm run lint
            - run: npm run build
