name: qa

on:
    push:
        branches: [master]
    pull_request:

jobs:
    php:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ["8.1"]
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  tools: cs2pr
            - uses: ramsey/composer-install@v2
            - run: composer php-cs-fixer -- --dry-run --format=checkstyle | cs2pr
            - run: composer phpstan -- --error-format=checkstyle | cs2pr
            - run: composer normalize --dry-run
    node:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["17.x"]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
            - uses: bahmutov/npm-install@v1
            - run: npx stylelint assets/scss
            - run: npx eslint assets/js
            - run:
                  npx prettier --check .github assets drush webpack.config.js babel.config.js
                  .eslintrc.js postcss.config.js prettier.config.js docker-compose.yaml servers.yaml
            - run: npx encore production
